#pragma GCC diagnostic ignored "-Wnon-virtual-dtor"
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wunused-but-set-variable"

#include "../inc/catch.hpp"
#include "../inc/catch2/trompeloeil.hpp"
#include "../src/nvapi_d3d.cpp"
#include "../src/nvapi_d3d11.cpp"
#include "../src/nvapi_d3d12.cpp"
#include "../src/nvapi_drs.cpp"
#include "../src/nvapi.cpp"
#include "../src/nvapi_sys.cpp"
#include "../src/nvapi_gpu.cpp"
#include "../src/nvapi_disp.cpp"
#include "../src/nvapi_mosaic.cpp"

#include "nvapi_sysinfo_mocks.cpp"
#include "nvapi_d3d_mocks.cpp"
#include "resource_factory_util.cpp"
#include "nvapi_d3d11_mocks.cpp"
#include "nvapi_d3d12_mocks.cpp"

#include "nvapi_d3d.cpp"
#include "nvapi_d3d11.cpp"
#include "nvapi_d3d12.cpp"
#include "nvapi_drs.cpp"
#include "nvapi_sysinfo.cpp"
