// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: nvapi.proto

#include "nvapi.pb.h"
#include "nvapi.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

static const char* DxvkNvapi_method_names[] = {
  "/DxvkNvapi/SetDwordSetting",
};

std::unique_ptr< DxvkNvapi::Stub> DxvkNvapi::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< DxvkNvapi::Stub> stub(new DxvkNvapi::Stub(channel, options));
  return stub;
}

DxvkNvapi::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SetDwordSetting_(DxvkNvapi_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status DxvkNvapi::Stub::SetDwordSetting(::grpc::ClientContext* context, const ::SetDwordSettingRequest& request, ::NvapiReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::SetDwordSettingRequest, ::NvapiReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetDwordSetting_, context, request, response);
}

void DxvkNvapi::Stub::async::SetDwordSetting(::grpc::ClientContext* context, const ::SetDwordSettingRequest* request, ::NvapiReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::SetDwordSettingRequest, ::NvapiReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetDwordSetting_, context, request, response, std::move(f));
}

void DxvkNvapi::Stub::async::SetDwordSetting(::grpc::ClientContext* context, const ::SetDwordSettingRequest* request, ::NvapiReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetDwordSetting_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NvapiReply>* DxvkNvapi::Stub::PrepareAsyncSetDwordSettingRaw(::grpc::ClientContext* context, const ::SetDwordSettingRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NvapiReply, ::SetDwordSettingRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetDwordSetting_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NvapiReply>* DxvkNvapi::Stub::AsyncSetDwordSettingRaw(::grpc::ClientContext* context, const ::SetDwordSettingRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetDwordSettingRaw(context, request, cq);
  result->StartCall();
  return result;
}

DxvkNvapi::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      DxvkNvapi_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< DxvkNvapi::Service, ::SetDwordSettingRequest, ::NvapiReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](DxvkNvapi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::SetDwordSettingRequest* req,
             ::NvapiReply* resp) {
               return service->SetDwordSetting(ctx, req, resp);
             }, this)));
}

DxvkNvapi::Service::~Service() {
}

::grpc::Status DxvkNvapi::Service::SetDwordSetting(::grpc::ServerContext* context, const ::SetDwordSettingRequest* request, ::NvapiReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


