// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: nvapi.proto
#ifndef GRPC_nvapi_2eproto__INCLUDED
#define GRPC_nvapi_2eproto__INCLUDED

#include "nvapi.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

class DxvkNvapi final {
 public:
  static constexpr char const* service_full_name() {
    return "DxvkNvapi";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SetDwordSetting(::grpc::ClientContext* context, const ::SetDwordSettingRequest& request, ::NvapiReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NvapiReply>> AsyncSetDwordSetting(::grpc::ClientContext* context, const ::SetDwordSettingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NvapiReply>>(AsyncSetDwordSettingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NvapiReply>> PrepareAsyncSetDwordSetting(::grpc::ClientContext* context, const ::SetDwordSettingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::NvapiReply>>(PrepareAsyncSetDwordSettingRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SetDwordSetting(::grpc::ClientContext* context, const ::SetDwordSettingRequest* request, ::NvapiReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SetDwordSetting(::grpc::ClientContext* context, const ::SetDwordSettingRequest* request, ::NvapiReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NvapiReply>* AsyncSetDwordSettingRaw(::grpc::ClientContext* context, const ::SetDwordSettingRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::NvapiReply>* PrepareAsyncSetDwordSettingRaw(::grpc::ClientContext* context, const ::SetDwordSettingRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SetDwordSetting(::grpc::ClientContext* context, const ::SetDwordSettingRequest& request, ::NvapiReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NvapiReply>> AsyncSetDwordSetting(::grpc::ClientContext* context, const ::SetDwordSettingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NvapiReply>>(AsyncSetDwordSettingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NvapiReply>> PrepareAsyncSetDwordSetting(::grpc::ClientContext* context, const ::SetDwordSettingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::NvapiReply>>(PrepareAsyncSetDwordSettingRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SetDwordSetting(::grpc::ClientContext* context, const ::SetDwordSettingRequest* request, ::NvapiReply* response, std::function<void(::grpc::Status)>) override;
      void SetDwordSetting(::grpc::ClientContext* context, const ::SetDwordSettingRequest* request, ::NvapiReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::NvapiReply>* AsyncSetDwordSettingRaw(::grpc::ClientContext* context, const ::SetDwordSettingRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::NvapiReply>* PrepareAsyncSetDwordSettingRaw(::grpc::ClientContext* context, const ::SetDwordSettingRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SetDwordSetting_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SetDwordSetting(::grpc::ServerContext* context, const ::SetDwordSettingRequest* request, ::NvapiReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SetDwordSetting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SetDwordSetting() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SetDwordSetting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetDwordSetting(::grpc::ServerContext* /*context*/, const ::SetDwordSettingRequest* /*request*/, ::NvapiReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetDwordSetting(::grpc::ServerContext* context, ::SetDwordSettingRequest* request, ::grpc::ServerAsyncResponseWriter< ::NvapiReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SetDwordSetting<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SetDwordSetting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SetDwordSetting() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::SetDwordSettingRequest, ::NvapiReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::SetDwordSettingRequest* request, ::NvapiReply* response) { return this->SetDwordSetting(context, request, response); }));}
    void SetMessageAllocatorFor_SetDwordSetting(
        ::grpc::MessageAllocator< ::SetDwordSettingRequest, ::NvapiReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::SetDwordSettingRequest, ::NvapiReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SetDwordSetting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetDwordSetting(::grpc::ServerContext* /*context*/, const ::SetDwordSettingRequest* /*request*/, ::NvapiReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetDwordSetting(
      ::grpc::CallbackServerContext* /*context*/, const ::SetDwordSettingRequest* /*request*/, ::NvapiReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SetDwordSetting<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SetDwordSetting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SetDwordSetting() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SetDwordSetting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetDwordSetting(::grpc::ServerContext* /*context*/, const ::SetDwordSettingRequest* /*request*/, ::NvapiReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SetDwordSetting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SetDwordSetting() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SetDwordSetting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetDwordSetting(::grpc::ServerContext* /*context*/, const ::SetDwordSettingRequest* /*request*/, ::NvapiReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetDwordSetting(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SetDwordSetting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SetDwordSetting() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SetDwordSetting(context, request, response); }));
    }
    ~WithRawCallbackMethod_SetDwordSetting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetDwordSetting(::grpc::ServerContext* /*context*/, const ::SetDwordSettingRequest* /*request*/, ::NvapiReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetDwordSetting(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SetDwordSetting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SetDwordSetting() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::SetDwordSettingRequest, ::NvapiReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::SetDwordSettingRequest, ::NvapiReply>* streamer) {
                       return this->StreamedSetDwordSetting(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SetDwordSetting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SetDwordSetting(::grpc::ServerContext* /*context*/, const ::SetDwordSettingRequest* /*request*/, ::NvapiReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSetDwordSetting(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::SetDwordSettingRequest,::NvapiReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SetDwordSetting<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SetDwordSetting<Service > StreamedService;
};


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_nvapi_2eproto__INCLUDED
