name: Build and test on Windows

on:
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-test-windows:
    runs-on: windows-2022

    steps:
    - name: Checkout code
      uses: actions/checkout@v7
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup Meson
      shell: pwsh
      run: pip install meson ninja

    - name: Find Visual Studio
      shell: pwsh
      run: |
        $installationPath = Get-VSSetupInstance `
          | Select-VSSetupInstance -Require Microsoft.VisualStudio.Workload.NativeDesktop -Latest `
          | Select-Object -ExpandProperty InstallationPath
        Write-Output "VSDEVCMD=${installationPath}\Common7\Tools\VsDevCmd.bat" `
          | Out-File -FilePath "${Env:GITHUB_ENV}" -Append

    - name: Print build version
      run: git describe --always --tags --dirty=+

    - name: Build MSVC x86
      shell: pwsh
      run: |
        & "${Env:COMSPEC}" /s /c "`"${Env:VSDEVCMD}`" -arch=x86 -host_arch=x64 -no_logo && set" `
          | % { , ($_ -Split '=', 2) } `
          | % { [System.Environment]::SetEnvironmentVariable($_[0], $_[1]) }
        meson setup --buildtype release --backend vs2022 build-msvc-x86 -Denable_tests=true
        msbuild -m build-msvc-x86\dxvk-nvapi.sln

    - name: Build MSVC x64
      shell: pwsh
      run: |
        & "${Env:COMSPEC}" /s /c "`"${Env:VSDEVCMD}`" -arch=x64 -host_arch=x64 -no_logo && set" `
          | % { , ($_ -Split '=', 2) } `
          | % { [System.Environment]::SetEnvironmentVariable($_[0], $_[1]) }
        meson setup --buildtype release --backend vs2022 build-msvc-x64 -Denable_tests=true
        msbuild -m build-msvc-x64\dxvk-nvapi.sln

    - name: Test MSVC x64
      shell: pwsh
      run: |
        $PSNativeCommandUseErrorActionPreference = $true
        .\build-msvc-x64\tests\nvapi64-tests.exe [@unit-tests]
        .\build-msvc-x64\tests\nvofapi64-tests.exe [@unit-tests]

    - name: Build MSVC ARM64EC
      shell: pwsh
      run: |
        & "${Env:COMSPEC}" /s /c "`"${Env:VSDEVCMD}`" -arch=arm64 -host_arch=x64 -no_logo && set" `
          | % { , ($_ -Split '=', 2) } `
          | % { [System.Environment]::SetEnvironmentVariable($_[0], $_[1]) }
        @"
        [binaries]
        cpp = 'cl'
        ar = 'lib'

        [built-in options]
        cpp_args = ['/arm64EC']
        cpp_link_args = ['/MACHINE:ARM64EC']

        [properties]
        needs_exe_wrapper = true

        [host_machine]
        system = 'windows'
        cpu_family = 'aarch64'
        cpu = 'aarch64'
        endian = 'little'
        "@ | Out-File -Encoding ascii build-arm64ec-msvc.txt
        meson setup --buildtype release --backend ninja --cross-file build-arm64ec-msvc.txt build-msvc-arm64ec
        ninja -C build-msvc-arm64ec

    - name: Build MSVC layer
      shell: pwsh
      run: |
        & "${Env:COMSPEC}" /s /c "`"${Env:VSDEVCMD}`" -arch=x64 -host_arch=x64 -no_logo && set" `
          | % { , ($_ -Split '=', 2) } `
          | % { [System.Environment]::SetEnvironmentVariable($_[0], $_[1]) }
        meson setup `
          --buildtype release `
          --backend vs2022 `
          '-Dcpp_args=/Zc:preprocessor' `
          '-Dabsolute_library_path=false' `
          '-Dlibrary_path_prefix=./' `
          '-Dmanifest_install_dir=.' `
          build-msvc-layer layer
        msbuild -m build-msvc-layer\dxvk-nvapi-vkreflex-layer.sln

    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: dxvk-nvapi-msvc
        path: |
          .\build-msvc-layer\VkLayer_*.json
          .\build-msvc-layer\*.dll
          .\build-msvc-*\src\*.dll
          .\build-msvc-*\tests\*.exe
